### ISSUE TITLE
Copy libgloss for newlib nano variant build

### ISSUE THREAD

**Issue by RynoAlberts** [stephanosio/zephyr-crosstool-ng#41]
Hi, the nano.specs file references libgloss_nano, however this file does not get created with the "Enable newlib nano" option.

I added the following code to the newlib.sh file in the newlib_copy_nano_multilibs() function and it seems to work. Is this the correct way to get Libgloss_nano?

CT_DoExecLog ALL cp -f "${nano_lib_dir}/${CT_TARGET}/lib/${multi_dir}/libgloss.a" \
                           "${CT_PREFIX_DIR}/${CT_TARGET}/lib/${multi_dir}/libgloss_nano.a"

Also, the option to "Optimize newlib for size" is enabled by default causing my libraries to increase dramatically in size.
I'm doing a Canadian cross build to build a riscv Windows toolchain.
Here are the sizes with "Optimize newlib for size" enabled.
libc                   1391 KB
libc_nano         2346 KB
libg                  1391 KB
libg_nano         2346 KB
libgloss             36 KB
libgloss_nano   60 KB

and without "Optimize newlib for size"  enabled.
libc                   1391 KB
libc_nano         1297 KB
libg                   1391 KB
libg_nano         1297 KB
libgloss             36 KB
libgloss_nano   36 KB

**Comment by stephanosio** [comment]
> I added the following code to the newlib.sh file in the newlib_copy_nano_multilibs() function and it seems to work. Is this the correct way to get Libgloss_nano?
> 
> CT_DoExecLog ALL cp -f "${nano_lib_dir}/${CT_TARGET}/lib/${multi_dir}/libgloss.a"
> "${CT_PREFIX_DIR}/${CT_TARGET}/lib/${multi_dir}/libgloss_nano.a"

That should work. I will look into this later after I get some basic issues sorted.

> Also, the option to "Optimize newlib for size" is enabled by default causing my libraries to increase dramatically in size.

This is because the nano variant with "--enable-target-optspace" option also enables debug information output (this can be considered a bug, or at least not ideal behaviour but newlib maintainers don't seem to buy it). Once you strip the nano libs, you will see that they are smaller than the full libs.

I will look into addressing this issue later #49 (I will probably just add this patch here: http://sourceware-org.1504.n7.nabble.com/PATCH-newlib-Remove-debug-flag-for-enable-target-optspace-td601171.html#a601389)
